version: '2'
networks:
  default:
    external:
      name: base_project
services:
  php:
    build: .
    volumes:
      - ./:/var/www/html/app
    environment:
       - DATABASE_NAME=postgres
       - DATABASE_USER=docker
       - DATABASE_PASSWORD=docker
       - DATABASE_HOST=db
    links:
       - "db"
  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes_from:
      - php
    volumes: 
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
       - "php"
    ports:
      - 80:80
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker