<?php

namespace AppBundle\Repository;

/**
 * CoinDaySnapshotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinDaySnapshotRepository extends \Doctrine\ORM\EntityRepository
{
}
