<?php

namespace AppBundle\Repository;

/**
 * CoinHourSnapshotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinHourSnapshotRepository extends \Doctrine\ORM\EntityRepository
{
}
