<?php

namespace AppBundle\Repository;

/**
 * CoinSnapshotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinSnapshotRepository extends \Doctrine\ORM\EntityRepository
{
}
