<?php

namespace AppBundle\Repository;

/**
 * HypeSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HypeSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
